// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njgvaakuevxyadrdimjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qZ3ZhYWt1ZXZ4eWFkcmRpbWp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTg1NjgsImV4cCI6MjA2MDgzNDU2OH0.6_EgeNXG0y9qoYFKXoTg7G-hc7KS7PRdKfEREm7qTTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);